name: Go Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.21']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v -o myapp-${{ matrix.os }} ./...
        shell: bash


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: ./myapp-${{ matrix.os }}


  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: List Artifact Contents
        run: ls


      - name: Checkout code
        uses: actions/checkout@v2


      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: ./myapp-${{ matrix.os }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.1
          release_name: Release exe
          draft: false
          prerelease: false