name: Go Build

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.21']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v -o myapp-${{ matrix.os }} ./...
        shell: bash


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: ./myapp-${{ matrix.os }}
