name: Go Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18' # Specify the Go version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v -o myapp ./... # Replace 'myapp' with your binary name and './...' with your project's path if necessary

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-binary
          path: ./myapp # Replace 'myapp' with your binary name